//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUDS入库
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR_TYPE
    {
        public CAR_TYPE()
        {
            this.VEHICLE = new HashSet<VEHICLE>();
        }
    
        public string ID { get; set; }
        public string TYPE { get; set; }
        public Nullable<short> AXLE_COUNT { get; set; }
        public Nullable<short> WHEEL_COUNT { get; set; }
        public Nullable<decimal> DIAMETER_UPPERBOUND1 { get; set; }
        public Nullable<decimal> DIAMETER_LOWERBOUND1 { get; set; }
        public Nullable<decimal> DIAMETER_UPPERBOUND2 { get; set; }
        public Nullable<decimal> DIAMETER_LOWERBOUND2 { get; set; }
        public Nullable<decimal> FLANGE_THICKNESS_UPPERBOUND1 { get; set; }
        public Nullable<decimal> FLANGE_THICKNESS_LOWERBOUND1 { get; set; }
        public Nullable<decimal> FLANGE_THICKNESS_UPPERBOUND2 { get; set; }
        public Nullable<decimal> FLANGE_THICKNESS_LOWERBOUND2 { get; set; }
        public Nullable<decimal> FLANGE_HEIGHT_UPPERBOUND1 { get; set; }
        public Nullable<decimal> FLANGE_HEIGHT_LOWERBOUND1 { get; set; }
        public Nullable<decimal> FLANGE_HEIGHT_UPPERBOUND2 { get; set; }
        public Nullable<decimal> FLANGE_HEIGHT_LOWERBOUND2 { get; set; }
        public Nullable<decimal> RIM_THICKNESS_UPPERBOUND1 { get; set; }
        public Nullable<decimal> RIM_THICKNESS_LOWERBOUND1 { get; set; }
        public Nullable<decimal> RIM_THICKNESS_UPPERBOUND2 { get; set; }
        public Nullable<decimal> RIM_THICKNESS_LOWERBOUND2 { get; set; }
        public Nullable<decimal> QR_UPPERBOUND1 { get; set; }
        public Nullable<decimal> QR_LOWERBOUND1 { get; set; }
        public Nullable<decimal> QR_UPPERBOUND2 { get; set; }
        public Nullable<decimal> QR_LOWERBOUND2 { get; set; }
        public Nullable<decimal> THREAD_WEAR_UPPERBOUND1 { get; set; }
        public Nullable<decimal> THREAD_WEAR_LOWERBOUND1 { get; set; }
        public Nullable<decimal> THREAD_WEAR_UPPERBOUND2 { get; set; }
        public Nullable<decimal> THREAD_WEAR_LOWERBOUND2 { get; set; }
        public Nullable<decimal> COXIAL_DIAM_DIFF_UPPERBOUND1 { get; set; }
        public Nullable<decimal> COXIAL_DIAM_DIFF_LOWERBOUND1 { get; set; }
        public Nullable<decimal> COXIAL_DIAM_DIFF_UPPERBOUND2 { get; set; }
        public Nullable<decimal> COXIAL_DIAM_DIFF_LOWERBOUND2 { get; set; }
        public Nullable<decimal> WHEELSET_DISTANCE_UPPERBOUND1 { get; set; }
        public Nullable<decimal> WHEELSET_DISTANCE_LOWERBOUND1 { get; set; }
        public Nullable<decimal> WHEELSET_DISTANCE_UPPERBOUND2 { get; set; }
        public Nullable<decimal> WHEELSET_DISTANCE_LOWERBOUND2 { get; set; }
        public Nullable<decimal> BOGIE_DIAM_DIFF_UPPERBOUND1 { get; set; }
        public Nullable<decimal> BOGIE_DIAM_DIFF_LOWERBOUND1 { get; set; }
        public Nullable<decimal> BOGIE_DIAM_DIFF_UPPERBOUND2 { get; set; }
        public Nullable<decimal> BOGIE_DIAM_DIFF_LOWERBOUND2 { get; set; }
        public Nullable<decimal> VEHICLE_DIAM_DIFF_UPPERBOUND1 { get; set; }
        public Nullable<decimal> VEHICLE_DIAM_DIFF_LOWERBOUND1 { get; set; }
        public Nullable<decimal> VEHICLE_DIAM_DIFF_UPPERBOUND2 { get; set; }
        public Nullable<decimal> VEHICLE_DIAM_DIFF_LOWERBOUND2 { get; set; }
    
        public virtual ICollection<VEHICLE> VEHICLE { get; set; }
    }
}
