//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUDS入库
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVICE_STATUS
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> CHECK_TIME { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> LIQUID_LEVEL { get; set; }
        public Nullable<decimal> WATER_TEMPERATURE { get; set; }
        public Nullable<decimal> A_TEMPERATURE { get; set; }
        public Nullable<decimal> B_TEMPERATURE { get; set; }
        public Nullable<decimal> ENVIRONMENT_TEMPERATURE { get; set; }
        public Nullable<decimal> DISK_SPACE { get; set; }
        public Nullable<System.DateTime> NEXT_CHECK_TIME { get; set; }
    }
}
