//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUDS入库
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECHECKS
    {
        public string ID { get; set; }
        public string FAULT_ID { get; set; }
        public string HANDLER { get; set; }
        public string SUGGESTION { get; set; }
        public string CONCLUSION { get; set; }
        public System.DateTime TIME { get; set; }
        public Nullable<decimal> VALUE { get; set; }
        public string RECHECK_PERSON { get; set; }
        public string STATE { get; set; }
    
        public virtual FAULT FAULT { get; set; }
    }
}
