//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUDS入库
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCRAPE_DEVICE_STATUS
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> TIME { get; set; }
        public string PLC { get; set; }
        public string UPS { get; set; }
        public string SENSOR1 { get; set; }
        public string SENSOR2 { get; set; }
        public string SENSOR3 { get; set; }
        public string SENSOR4 { get; set; }
        public string SENSOR5 { get; set; }
        public string SENSOR6 { get; set; }
    }
}
