//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUDS入库
{
    using System;
    using System.Collections.Generic;
    
    public partial class SITES
    {
        public SITES()
        {
            this.TRAIN = new HashSet<TRAIN>();
        }
    
        public string SITE_ID { get; set; }
        public string NAME { get; set; }
        public string CODE { get; set; }
        public string BUREAU_ID { get; set; }
        public string DEPOT_NAME { get; set; }
        public string CHECK_NAME { get; set; }
        public string PLANT_NAME { get; set; }
        public string DEVICE_ID { get; set; }
        public string FACTORY { get; set; }
        public string DEVICE_NAME { get; set; }
    
        public virtual ICollection<TRAIN> TRAIN { get; set; }
    }
}
