//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUDS入库
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATISTICS
    {
        public string ID { get; set; }
        public Nullable<short> YEAR { get; set; }
        public Nullable<short> MONTH { get; set; }
        public Nullable<short> SEASON { get; set; }
        public Nullable<short> DAY { get; set; }
        public Nullable<int> TRAIN_COUNT { get; set; }
        public Nullable<int> ALARM_COUNT { get; set; }
        public Nullable<int> DIMENSION_ALARM_COUNT { get; set; }
        public Nullable<int> INSPECTION_ALARM_COUNT { get; set; }
        public Nullable<int> SCRAPE_ALARM_COUNT { get; set; }
        public Nullable<int> ALARM_LEVEL1_COUNT { get; set; }
        public Nullable<int> ALARM_LEVEL2_COUNT { get; set; }
        public Nullable<int> ALARM_LEVEL3_COUNT { get; set; }
    }
}
