//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUDS入库
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAIN
    {
        public TRAIN()
        {
            this.VEHICLE = new HashSet<VEHICLE>();
            this.INSPECTION_DATA = new HashSet<INSPECTION_DATA>();
        }
    
        public string ID { get; set; }
        public string NAME { get; set; }
        public Nullable<short> AXLE_COUNT { get; set; }
        public System.DateTime DETECTION_TIME { get; set; }
        public string BUREAUDICT_ID { get; set; }
        public Nullable<short> ALARM_LEVEL { get; set; }
        public Nullable<short> INSPECTION_ALARM_LEVEL { get; set; }
        public Nullable<short> SCRAPE_ALARM_LEVEL { get; set; }
        public Nullable<short> DIMENSION_ALARM_LEVEL { get; set; }
        public Nullable<short> DIAMETER_ALARM_LEVEL { get; set; }
        public Nullable<short> FLANGE_THICKNESS_ALARM_LEVEL { get; set; }
        public Nullable<short> FLANGE_HEIGHT_ALARM_LEVEL { get; set; }
        public Nullable<short> RIM_THICKNESS_ALARM_LEVEL { get; set; }
        public Nullable<short> QR_ALARMLEVEL { get; set; }
        public string UNIT_NUMBER1 { get; set; }
        public string UNIT_NUMBER2 { get; set; }
        public string END_POSITION { get; set; }
        public Nullable<decimal> ARRIVE_SPEED { get; set; }
        public Nullable<decimal> LEAVE_SPEED { get; set; }
        public string SITE_ID { get; set; }
        public Nullable<short> ALARM1_COUNT { get; set; }
        public Nullable<short> ALARM2_COUNT { get; set; }
        public Nullable<short> INSPECTION_ALARM1_COUNT { get; set; }
        public Nullable<short> INSPECTION_ALARM2_COUNT { get; set; }
        public Nullable<short> SCRAPE_ALARM1_COUNT { get; set; }
        public Nullable<short> SCRAPE_ALARM2_COUNT { get; set; }
        public Nullable<short> THREADWEAR_ALARMLEVEL { get; set; }
        public Nullable<short> THREADWEAR_ALRAM1_COUNT { get; set; }
        public Nullable<short> THREADWEAR_ALRAM2_COUNT { get; set; }
        public Nullable<short> DIMENSION_ALARM1_COUNT { get; set; }
        public Nullable<short> DIMENSION_ALARM2_COUNT { get; set; }
        public Nullable<short> DIAMETER_ALARM1_COUNT { get; set; }
        public Nullable<short> DIAMETER_ALARM2_COUNT { get; set; }
        public Nullable<short> FLANGE_THICKNESS_ALARM1_COUNT { get; set; }
        public Nullable<short> FLANGE_THICKNESS_ALARM2_COUNT { get; set; }
        public Nullable<short> FLANGE_HEIGHT_ALARM1_COUNT { get; set; }
        public Nullable<short> FLANGE_HEIGHT_ALARM2_COUNT { get; set; }
        public Nullable<short> RIM_THICKNESS_ALARM1_COUNT { get; set; }
        public Nullable<short> RIM_THICKNESS_ALARM2_COUNT { get; set; }
        public Nullable<short> QR_ALARM1_COUNT { get; set; }
        public Nullable<short> QR_ALARM2_COUNT { get; set; }
        public string OPERATOR { get; set; }
        public string LAST_CHECK_ID { get; set; }
        public Nullable<short> CHECKED { get; set; }
        public Nullable<decimal> MAX_SPEED { get; set; }
        public Nullable<decimal> MIN_SPEED { get; set; }
        public string TRAIN_TYPE { get; set; }
        public Nullable<short> VEHICLE_COUNT { get; set; }
        public Nullable<short> LOCOMOTIVE_COUNT { get; set; }
        public string TRAIN_NO { get; set; }
        public Nullable<short> ALARM3_COUNT { get; set; }
        public Nullable<short> INSPECTION_ALARM3_COUNT { get; set; }
        public Nullable<short> SCRAPE_ALARM3_COUNT { get; set; }
        public Nullable<short> THREADWEAR_ALRAM3_COUNT { get; set; }
        public Nullable<short> DIMENSION_ALARM3_COUNT { get; set; }
        public Nullable<short> DIAMETER_ALARM3_COUNT { get; set; }
        public Nullable<short> FLANGE_THICKNESS_ALARM3_COUNT { get; set; }
        public Nullable<short> FLANGE_HEIGHT_ALARM3_COUNT { get; set; }
        public Nullable<short> RIM_THICKNESS_ALARM3_COUNT { get; set; }
        public Nullable<short> QR_ALARM3_COUNT { get; set; }
    
        public virtual BUREAUDICT BUREAUDICT { get; set; }
        public virtual SITES SITES { get; set; }
        public virtual ICollection<VEHICLE> VEHICLE { get; set; }
        public virtual ICollection<INSPECTION_DATA> INSPECTION_DATA { get; set; }
    }
}
