//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUDS入库
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TudsEntities : DbContext
    {
        public TudsEntities()
            : base("name=TudsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BUREAUDICT> BUREAUDICT { get; set; }
        public DbSet<CAR_TYPE> CAR_TYPE { get; set; }
        public DbSet<DEVICE_STATUS> DEVICE_STATUS { get; set; }
        public DbSet<FAULT> FAULT { get; set; }
        public DbSet<RECHECKS> RECHECKS { get; set; }
        public DbSet<SCRAPE_DEVICE_STATUS> SCRAPE_DEVICE_STATUS { get; set; }
        public DbSet<SITES> SITES { get; set; }
        public DbSet<STATISTICS> STATISTICS { get; set; }
        public DbSet<TRAIN> TRAIN { get; set; }
        public DbSet<VEHICLE> VEHICLE { get; set; }
        public DbSet<WHEEL> WHEEL { get; set; }
        public DbSet<DIMENSION_DATA> DIMENSION_DATA { get; set; }
        public DbSet<INSPECTION_DATA> INSPECTION_DATA { get; set; }
        public DbSet<SCRAPE_DATA> SCRAPE_DATA { get; set; }
    }
}
