//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUDS入库
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICLE
    {
        public VEHICLE()
        {
            this.WHEEL = new HashSet<WHEEL>();
        }
    
        public string ID { get; set; }
        public string NAME { get; set; }
        public string TRAIN_ID { get; set; }
        public string UNIT_NUMBER { get; set; }
        public string COACH_NUMBER { get; set; }
        public Nullable<short> PASS_ORDER { get; set; }
        public Nullable<short> ALARMLEVEL { get; set; }
        public Nullable<short> INSPECTION_ALARMLEVEL { get; set; }
        public Nullable<short> SCRAPE_ALARMLEVEL { get; set; }
        public Nullable<short> DIMENSION_ALARMLEVEL { get; set; }
        public Nullable<short> DIAMETER_ALARMLEVEL { get; set; }
        public Nullable<short> FLANGE_THICKNESS_ALARMLEVEL { get; set; }
        public Nullable<short> FLANGE_HEIGHT_ALARMLEVEL { get; set; }
        public Nullable<short> RIM_THICKNESS_ALARMLEVEL { get; set; }
        public Nullable<short> QR_ALARMLEVEL { get; set; }
        public Nullable<short> ALARM1_COUNT { get; set; }
        public Nullable<short> ALARM2_COUNT { get; set; }
        public Nullable<short> INSPECTION_ALARM1_COUNT { get; set; }
        public Nullable<short> INSPECTION_ALARM2_COUNT { get; set; }
        public Nullable<short> SCRAPE_ALARM1_COUNT { get; set; }
        public Nullable<short> SCRAPE_ALARM2_COUNT { get; set; }
        public Nullable<short> THREADWEAR_ALARMLEVEL { get; set; }
        public Nullable<short> THREADWEAR_ALRAM1_COUNT { get; set; }
        public Nullable<short> THREADWEAR_ALRAM2_COUNT { get; set; }
        public Nullable<short> DIMENSION_ALARM1_COUNT { get; set; }
        public Nullable<short> DIMENSION_ALARM2_COUNT { get; set; }
        public Nullable<short> DIAMETER_ALARM1_COUNT { get; set; }
        public Nullable<short> DIAMETER_ALARM2_COUNT { get; set; }
        public Nullable<short> FLANGE_THICKNESS_ALARM1_COUNT { get; set; }
        public Nullable<short> FLANGE_THICKNESS_ALARM2_COUNT { get; set; }
        public Nullable<short> FLANGE_HEIGHT_ALARM1_COUNT { get; set; }
        public Nullable<short> FLANGE_HEIGHT_ALARM2_COUNT { get; set; }
        public Nullable<short> RIM_THICKNESS_ALARM1_COUNT { get; set; }
        public Nullable<short> RIM_THICKNESS_ALARM2_COUNT { get; set; }
        public Nullable<short> QR_ALARM1_COUNT { get; set; }
        public Nullable<short> QR_ALARM2_COUNT { get; set; }
        public Nullable<short> IS_LOCOMOTIVE { get; set; }
        public string CAR_TYPE_ID { get; set; }
        public string AEI_END_DIRECTION { get; set; }
        public Nullable<short> ALARM3_COUNT { get; set; }
        public Nullable<short> INSPECTION_ALARM3_COUNT { get; set; }
        public Nullable<short> SCRAPE_ALARM3_COUNT { get; set; }
        public Nullable<short> THREADWEAR_ALRAM3_COUNT { get; set; }
        public Nullable<short> DIMENSION_ALARM3_COUNT { get; set; }
        public Nullable<short> DIAMETER_ALARM3_COUNT { get; set; }
        public Nullable<short> FLANGE_THICKNESS_ALARM3_COUNT { get; set; }
        public Nullable<short> FLANGE_HEIGHT_ALARM3_COUNT { get; set; }
        public Nullable<short> RIM_THICKNESS_ALARM3_COUNT { get; set; }
        public Nullable<short> QR_ALARM3_COUNT { get; set; }
    
        public virtual CAR_TYPE CAR_TYPE { get; set; }
        public virtual TRAIN TRAIN { get; set; }
        public virtual ICollection<WHEEL> WHEEL { get; set; }
    }
}
